### ISSUE TITLE
sys_errlist deprecated

### ISSUE THREAD

**Issue by maticm** [cyrus-and/httpfs#1]
[100%] Building C object CMakeFiles/httpfs.dir/fuse_api/unlink.c.o
Linking C executable httpfs
CMakeFiles/httpfs.dir/main.c.o: In function `main':
main.c:(.text+0x1eb): warning:`sys_errlist' is deprecated; use `strerror' or`strerror_r' instead
make[3]: Leaving directory `/var/www/httpfs/build-release'

I suggest changing line 38 of src/main.c from sys_errlist[errno] to strerror(errno)

**Comment by cyrus-and** [comment]
I agree, thanks for reporting.
