### ISSUE TITLE
errno 74 / Bad message

### ISSUE THREAD

**Issue by ghost** [cyrus-and/httpfs#6]
Hi,

using a fresh compiled version of httpfs (git master branch) I'm getting
'Unable to mount: errno (74) Bad message'.

In the case it matters, the webserver I'm connecting to is using PHP 5.6.12.

Could you please help me which screws to turn, to get this solved?

Thanks in advance,

Manfred

**Comment by cyrus-and** [comment]
Hi Manfred, cannot try right now, but can you please try again in debug mode and show me the output?

```
export HTTPFS_VERBOSE=1
```

before running `httpfs`. Please note that you will also have to re-generate the PHP script.

**Comment by ghost** [comment]
Hi Andrea,

sorry for having been dumb :(

The verbose call of httpfs gave a hint for the generated php file having been crippled while uploading to the server...

Please close the issue!

Thanks and sorry again,

Manfred

Am Mi, 09/09/2015 16:25, hat Andrea Cardaci notifications@github.com geschrieben:

**Comment by cyrus-and** [comment]
Hey, no problem! :)
